---
#  - name: Add signing key for Kubernetes
#    yum_key:
#      url: https://packages.cloud.google.com/yum/doc/yum-key.gpg
#      state: present

  - name: Adding apt repository for Kubernetes
    yum_repository:
      name: Kubernetes
      description: Kubernetes Repo
      baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64n
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled: yes
      file: kubernetes.list
      gpgcheck: no

  - name: Install Kubernetes binaries
    yum: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

#  - name: Configure node ip
#    lineinfile:
#      path: /etc/default/kubelet
#      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --node-name k8s-master

